#!/bin/sh

# PROVIDE: crazytrace
# REQUIRE: LOGIN NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=crazytrace
rcvar=crazytrace_enable

load_rc_config $name

: ${crazytrace_enable:="NO"}
: ${crazytrace_config:="/usr/local/etc/crazytrace.yaml"}

pidfile=/var/run/crazytrace.pid
command="/usr/sbin/daemon"
procname="/usr/local/bin/crazytrace"
command_args"
    --syslog \
    --syslog-facility daemon \
    --syslog-tag "$name"
command_args="-f -p ${pidfile} -T ${name} \
    /usr/bin/env PATH=$PATH:/usr/local/bin ${procname} \
    --server ${woodpeckeragent_server} \
    --grpc-token ${woodpeckeragent_token} \
    --grpc-secure true \
    --backend-engine local \
    --agent-config /usr/local/etc/woodpecker/agent.conf \
    --log-level info"

run_rc_command "$1"
