---
log_level: debug
crazytrace:
  - mac: 02:B1:4F:7E:9D:C3
    addresses: [fe80::2c0a:baff:fe2c:3d54]
    hoplimit: 255
    nodes:
      - addresses: [fd00::3]
        nodes:
          - addresses: [fd00::4]
