# SPDX-FileCopyrightText: Copyright (C) 2024-2025 Marek Küthe <m.k@mk16.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

labels:
  platform: freebsd/amd64

when:
  - event: manual
    branch: main
  - event: push
    branch: capsicum2

steps:
  - name: build
    image: sh
    commands:
      - pkg install --yes pkgconf gmake meson ninja boost-all yaml-cpp llvm
      # - make check
      # - make debian
      # - git clean -d --force
      # - rm --force --recursive build
      # - export CC=gcc CXX=g++
      - gmake
