when:
  - event: cron
    cron: build_crazytrace
    branch: main
  - event: manual
    branch: main
  - event: push

steps:
  - name: build
    image: codeberg.org/mark22k/ci:latest
    pull: true
    commands:
      - cd deb/
      - ./build.sh
      - curl --user $CODEBERG_GIT_USERNAME:$CODEBERG_GIT_PASSWORD --upload-file crazytrace.deb https://codeberg.org/api/packages/mark22k/debian/pool/bookworm/main/upload
    secrets:
      - codeberg_git_username
      - codeberg_git_password
